spring:
    jmx: 
        enabled: false
    profiles:
      active: ehcache
javafx:
    stage:
        resizable: true
    title: KimApp

browser:
  webUrlMap:
    home-url: http://192.168.0.156/webos/main.html
    appshop-url: http://www.kingyea.com.cn/portal/kingyea/